swagger:
  title: 一天博客系统接口文档
  description: 一天博客系统接口文档
  termsOfServiceUrl: https://github.com/erzhiqianyi/spring-boot-vue-blog
  author: 二之前一
  url: www.erzhiqianyi.com
  version: 1.0
  email: erzhiqianyi@gmail.com
  basePackage:  com.erzhiqianyi.yitian

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yitian?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: yitian
    password: yitian
    driverClassName: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 100

app:
  password:
    encoder:
      secret: 123456789
      iteration: 32
      length: 256
      algorithm: PBKDF2WithHmacSHA512
  jwt:
    secret: 123456789
logging:
  level:
    com:
      erzhiqianyi:
        yitian: debug

