swagger:
  title: 一天博客系统接口文档
  description: 一天博客系统接口文档
  termsOfServiceUrl: https://github.com/erzhiqianyi/spring-boot-vue-blog
  author: 二之前一
  url: www.erzhiqianyi.com
  version: 1.0
  email: erzhiqianyi@gmail.com
  basePackage: com.erzhiqianyi.blog.controller

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: blog
    password: blog
    driverClassName: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 100

logging:
  level:
    com:
      erzhiqianyi:
        blog: debug

